apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklin-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worklin-auth-service
  template:
    metadata:
      labels:
        app: worklin-auth-service
    spec:
      containers:
        - image: raneesa/worklin-auth-service:latest
          name: worklin-auth-service
          envFrom:
            - configMapRef:
                name: auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: worklin-auth-service
spec:
  selector:
    app: worklin-auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001