apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklin-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worklin-chat-service
  template:
    metadata:
      labels:
        app: worklin-chat-service
    spec:
      containers:
        - name: worklin-chat-service
          image: raneesa/worklin-chat-service:latest
          envFrom:
            - configMapRef:
                name: chat-config
---
apiVersion: v1
kind: Service
metadata:
  name: worklin-chat-service
spec:
  selector:
    app: worklin-chat-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004